#+TITLE: Scala
#+AUTHOR: Adolfo De Unánue
#+EMAIL: nanounanue@gmail.com
#+STARTUP: showeverything
#+STARTUP: nohideblocks
#+STARTUP: indent
#+PROPERTY: header-args:emacs-lisp :tangle ~/.config/emacs/elisp/setup-scala.el
#+PROPERTY:    header-args:shell  :tangle no
#+PROPERTY:    header-args        :results silent   :eval no-export   :comments org
#+OPTIONS:     num:nil toc:nil todo:nil tasks:nil tags:nil
#+OPTIONS:     skip:nil author:nil email:nil creator:nil timestamp:nil
#+INFOJS_OPT:  view:nil toc:nil ltoc:t mouse:underline buttons:0 path:http://orgmode.org/org-info.js


* [[https://ensime.github.io/][ENSIME]]

#+begin_quote
ENSIME was a Scala tooling project that lasted for ten years (2010
to 2019) and brought together hundreds of Free Software contributors
from diverse backgrounds. At its peak, 10% of Scala developers were
using ENSIME as their IDE for Scala.

ENSIME pioneered community-oriented development in the Scala community
and was the first to introduce a truly inclusive code of conduct.

In 2018, the Scala Center chose to fund a from-scratch competitor
named [[https://scalameta.org/metals/][Metals]]. As a result, ENSIME is no longer relevant.

Users are encouraged to install Metals.

Contributors are encouraged to do something else with their precious
time: spend it with family or surrounded by nature. You will not find
happiness by engaging with the Scala Open Source community; only
exploitation, politics and drama. If you insist on getting involved,
please [[https://medium.com/@fommil/hide-your-real-name-in-open-source-3d67e74a8c56][do not use your real name]].
#+end_quote

Entonces ya no usaremos =ensime= ...


#+BEGIN_SRC emacs-lisp :tangle no
  (use-package ensime
    :config
    (setq ensime-startup-notification nil
          ensime-startup-snapshot-notification nil))

#+END_SRC

* SBT

#+BEGIN_SRC emacs-lisp
  (use-package sbt-mode
               :commands sbt-start sbt-command
               :config
               ;; WORKAROUND: https://github.com/ensime/emacs-sbt-mode/issues/31
               ;; allows using SPACE when in the minibuffer
               (substitute-key-definition
                'minibuffer-complete-word
                'self-insert-command
                minibuffer-local-completion-map)
               (add-hook 'sbt-mode-hook
                         (lambda ()
                           (setq prettify-symbols-alist
                                 `((,(expand-file-name (directory-file-name default-directory)) . ?⌂)
                                   (,(expand-file-name "~") . ?~)))
                           (prettify-symbols-mode t)))

               )
#+END_SRC


* Scala

#+BEGIN_SRC emacs-lisp
  (use-package scala-mode
    :mode (
           ("\\.scala$" . scala-mode)
           )
    :config
      (add-hook 'scala-mode-hook
                '(lambda ()
                   (yas/minor-mode-on)
                   (scala-mode-feature-electric-mode)))
      (add-hook 'scala-mode-hook 'ensime-scala-mode-hook))

#+END_SRC

* Al final

#+BEGIN_SRC emacs-lisp
  (provide 'setup-scala)
#+END_SRC
