#+TITLE:  Emacs: Configuración de clientes
#+AUTHOR: Adolfo De Unánue
#+EMAIL:  nanounanue@gmail.com
#+STARTUP: showeverything
#+STARTUP: nohideblocks
#+STARTUP: indent
#+PROPERTY:    header-args:emacs-lisp  :tangle ~/.emacs.d/elisp/setup-client.el
#+PROPERTY:    header-args:shell  :tangle no
#+PROPERTY:    header-args        :results silent   :eval no-export   :comments org
#+OPTIONS:     num:nil toc:nil todo:nil tasks:nil tags:nil
#+OPTIONS:     skip:nil author:nil email:nil creator:nil timestamp:nil
#+INFOJS_OPT:  view:nil toc:nil ltoc:t mouse:underline buttons:0 path:http://orgmode.org/org-info.js
#+TAGS:   emacs

Configuración para clientes gráficos

* Generalidades

No usar /dialog-boxes/

#+BEGIN_SRC emacs-lisp
(setq use-dialog-box nil)
#+END_SRC


* /Key Bindings/

El artículo [[http://emacsninja.com/posts/making-emacs-more-presentable.html][Making Emacs More Presentable]], muestra este truco que
cambia el tamaño de la fuente, en la /window/ no el /buffer/

#+begin_src emacs-lisp
(use-package default-text-scale)
#+end_src

  #+BEGIN_SRC emacs-lisp
    (defun nanounanue/text-scale-frame-change (fn)
      (let* ((current-font-name (frame-parameter nil 'font))
             (decomposed-font-name (x-decompose-font-name current-font-name))
             (font-size (string-to-int (aref decomposed-font-name 5))))
        (aset decomposed-font-name 5 (int-to-string (funcall fn font-size)))
        (set-frame-font (x-compose-font-name decomposed-font-name))))

    (defun nanounanue/text-scale-frame-increase ()
      (interactive)
      (nanounanue/text-scale-frame-change '1+))

    (defun nanounanue/text-scale-frame-decrease ()
      (interactive)
      (nanounanue/text-scale-frame-change '1-))

    (bind-keys
     ("s-C-+" . nanounanue/text-scale-frame-increase)
     ("A-C-+" . nanounanue/text-scale-frame-increase)
     ("s-C-=" . nanounanue/text-scale-frame-increase)
     ("A-C-=" . nanounanue/text-scale-frame-increase)
     ("s-C--" . nanounanue/text-scale-frame-decrease)
     ("A-C--" . nanounanue/text-scale-frame-decrease))
  #+END_SRC


* Fuentes

Definimos algunas variables

#+begin_src emacs-lisp
(defvar  nanounanue-font-default)
(defvar  nanounanue-font-variable)
(defvar  nanounanue-font-modeline)
#+end_src

Asignamos las variables


#+begin_src emacs-lisp
(setq
 nanounanue-font-default "Fira Code"
 nanounanue-font-variable "Ubuntu Mono" ;; Noto Mono
 nanounanue-font-modeline "DejaVu Sans Mono")
#+end_src




Activar /syntax highlighting/ globalmente

 #+BEGIN_SRC emacs-lisp
 (global-font-lock-mode 1)
 #+END_SRC

¡Hay tantas opciones! Y yo  nunca me decido. Ver [[file:~/dotfiles/fonts.org][aquí]] para instalarlas.


Para ver que familias de fuentes están disponibles:

#+BEGIN_SRC emacs-lisp :tangle no
(message "%s" (font-family-list))
#+END_SRC


Instrucciones [[http://ergoemacs.org/emacs/emacs_list_and_set_font.html][aquí]]

#+BEGIN_SRC emacs-lisp
(set-face-attribute 'default nil
                    :family nanounanue-font-default
                    :height 150
                    :weight 'normal)
(set-face-attribute 'mode-line nil :family nanounanue-font-modeline :height 150 :weight 'regular)
(set-face-attribute 'fixed-pitch nil :family nanounanue-font-default :height 150)
(set-face-attribute 'variable-pitch nil :family nanounanue-font-variable)
#+END_SRC

Ajustando las fuentes dependiendo del tamaño del monitor

#+begin_src emacs-lisp
(when (display-graphic-p)
  (if (> (x-display-pixel-width) 1800)
      (if ;; very large number of pixels in display. side-by-side?
          (> (x-display-pixel-width) 5000)
	      (nanounanue/setup-main-fonts 140 140 120)
        (if (or
             (and             ;; specific display
              (= (x-display-pixel-width) 2560)
              (= (x-display-pixel-height) 1600))
             (and ;; another specific display setup
              (= (x-display-pixel-width) 3840)
              (= (x-display-pixel-height) 1080)))
            (nanounanue/setup-main-fonts 140 140 120)

          ;; other large display
	      (nanounanue/setup-main-fonts 140 140 120)
          ))
	(nanounanue-setup/main-fonts 140 140 120)))
#+end_src


#+begin_src emacs-lisp :tangle no
(set-frame-font "Fira Code-14" t)
#+end_src

#+BEGIN_SRC emacs-lisp
  (use-feature text-mode
    :demand t
    :hook (text-mode . (lambda ()
                         (variable-pitch-mode 1))))
#+END_SRC


#+BEGIN_SRC emacs-lisp :tangle no
(use-package typo
  ;ensure t
  :config
  (typo-global-mode 1)
  (add-hook 'text-mode-hook 'typo-mode))
#+END_SRC

Por último habilitamos en el mismo /buffer/ paralabras con /pitch/
variable (para texto) y fijas (para código)

#+begin_src emacs-lisp
(use-package mixed-pitch
  :demand t
  :hook
  (text-mode . mixed-pitch-mode))
#+end_src



** Paréntesis

Agrega /face/ a los paréntesis, de tal manera que los temas puedan oscurecerlos

#+BEGIN_SRC emacs-lisp
(use-package paren-face
  ;ensure t
  :init (global-paren-face-mode))
#+END_SRC

*  [[https://emacsthemes.com/popular/index.html][Temas]]

** Zenburn

#+BEGIN_SRC emacs-lisp
  (use-package zenburn-theme
    ;ensure t
    :config
    ;; use variable-pitch fonts for some headings and titles
    (setq zenburn-use-variable-pitch t)

    ;; scale headings in org-mode
    (setq zenburn-scale-org-headlines t)

    ;; scale headings in outline-mode
    (setq zenburn-scale-outline-headlines t))
#+END_SRC

** Solarized

#+BEGIN_SRC emacs-lisp
  (use-package solarized-theme
    ;ensure t
    :config
    (setq x-underline-at-descent-line t))
#+END_SRC

** Gruvbox

#+BEGIN_SRC emacs-lisp
(use-package gruvbox-theme)
#+END_SRC


** Poet

#+BEGIN_SRC emacs-lisp
(use-package poet-theme)
#+END_SRC

** Nord

#+BEGIN_SRC emacs-lisp
(use-package nord-theme
  :config
  (add-to-list 'custom-theme-load-path (expand-file-name "~/.emacs.d/themes/"))
  (load-theme 'nord t))

(use-package doom-modeline
  :defer 0.1
  :config (doom-modeline-mode))

(use-package fancy-battery
  :after doom-modeline
  :hook (after-init . fancy-battery-mode))
#+END_SRC

** Zerodark

#+begin_src emacs-lisp
(use-package zerodark-theme)
#+end_src

** Seleccionando el tema dependiendo del ambiente

#+begin_src emacs-lisp
(if (display-graphic-p)
    ;; (load-theme 'abyss 'no-confirm)
    (load-theme 'zerodark 'no-confirm)
  (load-theme 'wheatgrass))  ;; wheatgrass included in emacs
#+end_src


* all-the-icons

#+BEGIN_SRC emacs-lisp
(use-package all-the-icons)
#+END_SRC

#+BEGIN_SRC emacs-lisp :tangle no
(all-the-icons-install-fonts)
#+END_SRC

Integrarlo con [[file:emacs-ivy.org][ivy y counsel]]
#+BEGIN_SRC emacs-lisp
(use-package all-the-icons-ivy
  :demand t
  :after (all-the-icons ivy)
  :custom (all-the-icons-ivy-file-commands '(counsel-dired-jump
                                             counsel-find-file
                                             counsel-file-jump
                                             counsel-find-library
                                             counsel-git
                                             counsel-projectile-find-dir
                                             counsel-projectile-find-file
                                             counsel-recentf))
  (all-the-icons-ivy-buffer-commands '(ivy-switch-buffer-other-window))
  :config
  (add-to-list 'all-the-icons-ivy-file-commands 'counsel-dired-jump)
  (add-to-list 'all-the-icons-ivy-file-commands 'counsel-find-library)
  (all-the-icons-ivy-setup))
#+END_SRC

 =dired=

#+BEGIN_SRC emacs-lisp
(use-package all-the-icons-dired
  :demand t
  :config
  (add-hook 'dired-mode-hook 'all-the-icons-dired-mode))

#+END_SRC

Y finalmente =company-box= (/Front end/ con íconos para =company=)

#+BEGIN_SRC emacs-lisp
(use-package company-box
  :after company
  :diminish
  :hook (company-mode . company-box-mode))
#+END_SRC


* mode-line

Por el momento uso [[https://github.com/Malabarba/smart-mode-line/][smart-mode-line]]

#+BEGIN_SRC emacs-lisp
(use-package smart-mode-line
  :demand t
  :config
  (setq sml/shorten-directory t)
  (setq sml/shorten-modes t)
  (setq sml/no-confirm-load-theme t)
  (sml/setup))
#+END_SRC


* Dashboard

|----------------------------+------------------|
| Shortcut                   | Function         |
|----------------------------+------------------|
| Tab Or C-i                 | Next Item        |
| Shift-Tab                  | Previous Item    |
| Return / Mouse Click / C-m | Open             |
| r                          | Recent files     |
| m                          | Bookmarks        |
| p                          | Projects         |
| a                          | Org-Mode Agenda  |
| e                          | Registers        |
| g                          | Refresh contents |
| {                          | Previous section |
| }                          | Next section     |

#+BEGIN_SRC emacs-lisp
(use-package dashboard
  :demand t
  :preface
  (defun nanounanue/dashboard-banner ()
    "Sets a dashboard banner including information on package initialization
     time and garbage collections."
    (setq dashboard-banner-logo-title
          (format "Emacs ready in %.2f seconds with %d garbage collections."
                  (float-time
                   (time-subtract after-init-time before-init-time)) gcs-done)))
  :hook
  (dashboard-mode . nanounanue/dashboard-banner)
  :custom
  (dashboard-startup-banner 'official)
  ;; Content is not centered by default. To center, set
  (dashboard-center-content t)

  ;; To disable shortcut "jump" indicators for each section, set
  (dashboard-show-shortcuts t)
  (dashboard-set-heading-icons t)
  (dashboard-set-file-icons t)
  (dashboard-items '((recents  . 5)
                     (projects . 5)))

  ;;To show info about the packages loaded and the init time:
  (dashboard-set-init-info t)

  :config
  (dashboard-setup-startup-hook))
#+END_SRC

* Zoom

#+begin_src emacs-lisp
(use-package zoom-frm)
#+end_src

* Tabs

*NOTA*: Deshabilitado, no agrega valor y ocupa mucho espacio

#+begin_src emacs-lisp
(use-package centaur-tabs
  :disabled t
  :config
  (setq centaur-tabs-style "bar")
  (setq centaur-tabs-height 30)
  (setq centaur-tabs-modified-marker "●")
  (setq centaur-tabs-set-icons t)
  (setq centaur-tabs-set-bar 'over)
  (setq centaur-tabs-set-modified-marker t)
  (centaur-tabs-headline-match)
  (centaur-tabs-mode t)
  :bind
  ("C-<prior>" . centaur-tabs-backward)
  ("C-<next>" . centaur-tabs-forward))
#+end_src

* Clientes

** [[https://github.com/syohex/emacs-emamux/][Emamux]]

¡Controla =tmux= desde Emacs!

#+begin_src emacs-lisp
(use-package emamux)
#+end_src

** Pocket Reader

Uno de los elementos *indispensables* para una experiencia de lectura
rica es =pocket=:

#+begin_src emacs-lisp :tangle no
(use-package pocket-reader)
#+end_src

La primera vez, ejecuta

#+begin_src emacs-lisp :tangle no
(pocket-reader)
#+end_src


Y luego sigue las instrucciones.


* Al final

#+BEGIN_SRC emacs-lisp
(provide 'setup-client)
#+END_SRC
